---
feather1:
- paramID: '0'
  paramValue: '30'
# - paramID: '1'
#  paramValue: '0'
# - paramID: '2'
#  paramValue: '125000'
# - paramID: '3'
#   paramValue: '1500'
# - paramID: '4'
#   paramValue: '5'
# - paramID: '5'
#   paramValue: '100'
# - paramID: '6'
#   paramValue: '0'
# - paramID: '7'
#   paramValue: '0'
# - paramID: '8'
#   paramValue: '0'
# - paramID: '9'
#   paramValue: '0'
# - paramID: '10'
#   paramValue: '0'
# - paramID: '11'
#   paramValue: '0'
# - paramID: '12'
#   paramValue: '0'
# - paramID: '13'
#   paramValue: '255'
# - paramID: '14'
#   paramValue: '0'
feather2:
- paramID: '0'
  paramValue: '30'
#- paramID: '1'
#  paramValue: '0'
#- paramID: '2'
#  paramValue: '125000'
# - paramID: '3'
#   paramValue: '1500'
# - paramID: '4'
#   paramValue: '5'
# - paramID: '5'
#   paramValue: '100'
# - paramID: '6'
#   paramValue: '0'
# - paramID: '7'
#   paramValue: '0'
# - paramID: '8'
#   paramValue: '0'
# - paramID: '9'
#   paramValue: '0'
# - paramID: '10'
#   paramValue: '0'
# - paramID: '11'
#   paramValue: '0'
# - paramID: '12'
#   paramValue: '0'
# - paramID: '13'
#   paramValue: '255'
# - paramID: '14'
#   paramValue: '0'
feather3:
- paramID: '0'
  paramValue: '30'
# - paramID: '1'
#  paramValue: '0'
# - paramID: '2'
#  paramValue: '125000'
# - paramID: '3'
#   paramValue: '1500'
# - paramID: '4'
#   paramValue: '5'
# - paramID: '5'
#   paramValue: '100'
# - paramID: '6'
#   paramValue: '0'
# - paramID: '7'
#   paramValue: '0'
# - paramID: '8'
#   paramValue: '0'
# - paramID: '9'
#   paramValue: '0'
# - paramID: '10'
#   paramValue: '0'
# - paramID: '11'
#   paramValue: '0'
# - paramID: '12'
#   paramValue: '0'
# - paramID: '13'
#   paramValue: '255'
# - paramID: '14'
#   paramValue: '0'
feather4:
- paramID: '0'
  paramValue: '30'
# - paramID: '1'
#  paramValue: '0'
# - paramID: '2'
#  paramValue: '125000'
# - paramID: '3'
#   paramValue: '1500'
# - paramID: '4'
#   paramValue: '5'
# - paramID: '5'
#   paramValue: '100'
# - paramID: '6'
#   paramValue: '0'
# - paramID: '7'
#   paramValue: '0'
# - paramID: '8'
#   paramValue: '0'
# - paramID: '9'
#   paramValue: '0'
# - paramID: '10'
#   paramValue: '0'
# - paramID: '11'
#   paramValue: '0'
# - paramID: '12'
#   paramValue: '0'
# - paramID: '13'
#   paramValue: '255'
# - paramID: '14'
#   paramValue: '0'
feather5:
- paramID: '0'
  paramValue: '30'
# - paramID: '1'
#  paramValue: '0'
# - paramID: '2'
#  paramValue: '125000'
# - paramID: '3'
#   paramValue: '1500'
# - paramID: '4'
#   paramValue: '5'
# - paramID: '5'
#   paramValue: '100'
# - paramID: '6'
#   paramValue: '0'
# - paramID: '7'
#   paramValue: '0'
# - paramID: '8'
#   paramValue: '0'
# - paramID: '9'
#   paramValue: '0'
# - paramID: '10'
#   paramValue: '0'
# - paramID: '11'
#   paramValue: '0'
# - paramID: '12'
#   paramValue: '0'
# - paramID: '13'
#   paramValue: '255'
# - paramID: '14'
#   paramValue: '0'
